{"name": "test_send_message_error_handling", "status": "passed", "description": "Test error handling in send_message.", "attachments": [{"name": "log", "source": "39fd4708-7933-42af-9dd4-f62051a754cb-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "cef04645-e7fb-4deb-9582-562f9ca1bebf-attachment.txt", "type": "text/plain"}], "start": 1753819432433, "stop": 1753819432434, "uuid": "20f06a68-da52-4a56-8d86-8c1bd6efe332", "historyId": "dae6946a25eb42b2c392425cf1e0c2bd", "testCaseId": "dae6946a25eb42b2c392425cf1e0c2bd", "fullName": "tests.unit.core.test_notification_manager.TestErrorHandling#test_send_message_error_handling", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_notification_manager"}, {"name": "subSuite", "value": "TestErrorHandling"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_notification_manager"}], "titlePath": ["tests", "unit", "core", "test_notification_manager.py", "TestErrorHandling"]}