{"name": "test_error_recovery_workflow_e2e", "status": "passed", "description": "E2E: Workflow with error recovery and retry mechanisms.", "attachments": [{"name": "log", "source": "aa6803b8-333e-474b-a696-6e732c89c462-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "258e5078-66e6-4933-ad0e-8da58009ab55-attachment.txt", "type": "text/plain"}], "start": 1753819409296, "stop": 1753819409614, "uuid": "f535dfb6-8c51-42a2-a916-93ccb29cf830", "historyId": "5caf375cafa971eb9fdc941b8cb725cc", "testCaseId": "5caf375cafa971eb9fdc941b8cb725cc", "fullName": "tests.e2e.workflows.test_complete_workflow_e2e.TestCompleteWorkflowE2E#test_error_recovery_workflow_e2e", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.e2e.workflows"}, {"name": "suite", "value": "test_complete_workflow_e2e"}, {"name": "subSuite", "value": "TestCompleteWorkflowE2E"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.e2e.workflows.test_complete_workflow_e2e"}], "titlePath": ["tests", "e2e", "workflows", "test_complete_workflow_e2e.py", "TestCompleteWorkflowE2E"]}