{"name": "test_multiple_issues", "status": "passed", "description": "Test validation with multiple issues in one file.", "start": 1753819436352, "stop": 1753819436354, "uuid": "0d098934-90ca-4288-a5d8-dabd2f496af3", "historyId": "2bf7a51bca82a522a2b1b79ee6dbcd9d", "testCaseId": "2bf7a51bca82a522a2b1b79ee6dbcd9d", "fullName": "tests.unit.core.test_validate_agent_resources_coverage.TestValidateAgentResources#test_multiple_issues", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_validate_agent_resources_coverage"}, {"name": "subSuite", "value": "TestValidateAgentResources"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_validate_agent_resources_coverage"}], "titlePath": ["tests", "unit", "core", "test_validate_agent_resources_coverage.py", "TestValidateAgentResources"]}