{"name": "test_global_instances_exist", "status": "passed", "description": "Test dat globale instances bestaan.", "start": 1753819430201, "stop": 1753819430201, "uuid": "d546de4c-8a77-4191-947f-25570446f5fe", "historyId": "4e660b4141b5288e47840a023fded270", "testCaseId": "4e660b4141b5288e47840a023fded270", "fullName": "tests.unit.core.test_monitoring_coverage.TestGlobalInstances#test_global_instances_exist", "labels": [{"name": "parentSuite", "value": "tests.unit.core"}, {"name": "suite", "value": "test_monitoring_coverage"}, {"name": "subSuite", "value": "TestGlobalInstances"}, {"name": "host", "value": "Yannick-Mac-Gillavry-werk.local"}, {"name": "thread", "value": "90219-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.core.test_monitoring_coverage"}], "titlePath": ["tests", "unit", "core", "test_monitoring_coverage.py", "TestGlobalInstances"]}